-> Coatl01

=== Coatl01 ===
Mi hermano me contó sobre tí...
Sobre como lo liberaste, no podía creerlo. Ahora estoy agradecido contigo.
Somos “Coatl” somos guardianes de la tierra y del conocimiento oculto...
Siempre estaré contigo...
-> DONE